mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
proxies:
- name: US-AT&T-1
  type: socks5
  server: 68.71.247.130
  port: 4145
  udp: true
- name: US-AT&T-2
  type: socks5
  server: 68.71.251.134
  port: 4145
  udp: true
- name: US-Cox-3
  type: socks5
  server: 184.181.217.220
  port: 4145
  udp: true
- name: US-Cox-4
  type: socks5
  server: 184.178.172.11
  port: 4145
  udp: true
- name: US-Cox-5
  type: socks5
  server: 184.178.172.13
  port: 15311
  udp: true
- name: US-Cox-6
  type: socks5
  server: 184.181.217.213
  port: 4145
  udp: true
- name: US-Cox-7
  type: socks5
  server: 174.77.111.196
  port: 4145
  udp: true
- name: US-Cox-8
  type: socks5
  server: 174.77.111.198
  port: 49547
  udp: true
- name: US-Cox-9
  type: socks5
  server: 70.166.167.55
  port: 57745
  udp: true
- name: US-Cox-10
  type: socks5
  server: 184.181.217.194
  port: 4145
  udp: true
- name: US-Cox-11
  type: socks5
  server: 184.181.217.206
  port: 4145
  udp: true
- name: US-AT&T-12
  type: socks5
  server: 68.71.249.153
  port: 48606
  udp: true
- name: US-Cox-13
  type: socks5
  server: 174.77.111.197
  port: 4145
  udp: true
- name: US-Cox-14
  type: socks5
  server: 184.181.217.201
  port: 4145
  udp: true
- name: US-Cox-15
  type: socks5
  server: 184.178.172.5
  port: 15303
  udp: true
- name: US-Cox-16
  type: socks5
  server: 184.178.172.14
  port: 4145
  udp: true
- name: US-Cox-17
  type: socks5
  server: 184.181.217.210
  port: 4145
  udp: true
- name: US-Cox-18
  type: socks5
  server: 184.178.172.23
  port: 4145
  udp: true
- name: US-Cox-19
  type: socks5
  server: 184.178.172.25
  port: 15291
  udp: true
- name: US-Cox-20
  type: socks5
  server: 184.178.172.3
  port: 4145
  udp: true
- name: US-Cox-21
  type: socks5
  server: 174.64.199.79
  port: 4145
  udp: true
- name: US-Cox-22
  type: socks5
  server: 184.178.172.26
  port: 4145
  udp: true
- name: US-AT&T-23
  type: socks5
  server: 68.71.245.206
  port: 4145
  udp: true
- name: US-AT&T-24
  type: socks5
  server: 68.71.249.158
  port: 4145
  udp: true
- name: US-AT&T-25
  type: socks5
  server: 68.71.241.33
  port: 4145
  udp: true
- name: US-AT&T-26
  type: socks5
  server: 68.71.243.14
  port: 4145
  udp: true
- name: US-AT&T-27
  type: socks5
  server: 68.71.252.38
  port: 4145
  udp: true
- name: US-Cox-28
  type: socks5
  server: 174.75.211.222
  port: 4145
  udp: true
- name: US-Cox-29
  type: socks5
  server: 70.166.167.38
  port: 57728
  udp: true
- name: US-Cox-30
  type: socks5
  server: 184.181.178.33
  port: 4145
  udp: true
- name: US-AT&T-31
  type: socks5
  server: 68.71.240.210
  port: 4145
  udp: true
- name: US-Cox-32
  type: socks5
  server: 70.166.65.160
  port: 4145
  udp: true
- name: US-AT&T-33
  type: socks5
  server: 68.71.242.118
  port: 4145
  udp: true
- name: US-Cox-34
  type: socks5
  server: 174.64.199.82
  port: 4145
  udp: true
- name: US-Cox-35
  type: socks5
  server: 174.75.211.193
  port: 4145
  udp: true
- name: US-Cox-36
  type: socks5
  server: 184.185.2.12
  port: 4145
  udp: true
- name: US-Cox-37
  type: socks5
  server: 184.178.172.28
  port: 15294
  udp: true
- name: US-Cox-38
  type: socks5
  server: 184.182.240.12
  port: 4145
  udp: true
- name: US-Cox-39
  type: socks5
  server: 184.178.172.18
  port: 15280
  udp: true
- name: US-AT&T-40
  type: socks5
  server: 68.71.254.6
  port: 4145
  udp: true
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - DIRECT
  - US-AT&T-1
  - US-AT&T-2
  - US-Cox-3
  - US-Cox-4
  - US-Cox-5
  - US-Cox-6
  - US-Cox-7
  - US-Cox-8
  - US-Cox-9
  - US-Cox-10
  - US-Cox-11
  - US-AT&T-12
  - US-Cox-13
  - US-Cox-14
  - US-Cox-15
  - US-Cox-16
  - US-Cox-17
  - US-Cox-18
  - US-Cox-19
  - US-Cox-20
  - US-Cox-21
  - US-Cox-22
  - US-AT&T-23
  - US-AT&T-24
  - US-AT&T-25
  - US-AT&T-26
  - US-AT&T-27
  - US-Cox-28
  - US-Cox-29
  - US-Cox-30
  - US-AT&T-31
  - US-Cox-32
  - US-AT&T-33
  - US-Cox-34
  - US-Cox-35
  - US-Cox-36
  - US-Cox-37
  - US-Cox-38
  - US-Cox-39
  - US-AT&T-40
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  proxies:
  - US-AT&T-1
  - US-AT&T-2
  - US-Cox-3
  - US-Cox-4
  - US-Cox-5
  - US-Cox-6
  - US-Cox-7
  - US-Cox-8
  - US-Cox-9
  - US-Cox-10
  - US-Cox-11
  - US-AT&T-12
  - US-Cox-13
  - US-Cox-14
  - US-Cox-15
  - US-Cox-16
  - US-Cox-17
  - US-Cox-18
  - US-Cox-19
  - US-Cox-20
  - US-Cox-21
  - US-Cox-22
  - US-AT&T-23
  - US-AT&T-24
  - US-AT&T-25
  - US-AT&T-26
  - US-AT&T-27
  - US-Cox-28
  - US-Cox-29
  - US-Cox-30
  - US-AT&T-31
  - US-Cox-32
  - US-AT&T-33
  - US-Cox-34
  - US-Cox-35
  - US-Cox-36
  - US-Cox-37
  - US-Cox-38
  - US-Cox-39
  - US-AT&T-40
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
rules:
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
