mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
tcp-concurrent: true
external-controller: 127.0.0.1:9090
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - 223.5.5.5
  - 223.6.6.6
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
proxies:
- name: ğŸ‡ºğŸ‡¸ AT&T-206
  type: socks5
  server: 68.71.245.206
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-14
  type: socks5
  server: 68.71.243.14
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-158
  type: socks5
  server: 68.71.249.158
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-134
  type: socks5
  server: 68.71.251.134
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-6
  type: socks5
  server: 68.71.254.6
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-38
  type: socks5
  server: 68.71.252.38
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-153
  type: socks5
  server: 68.71.249.153
  port: 48606
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-130
  type: socks5
  server: 68.71.247.130
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-33
  type: socks5
  server: 68.71.241.33
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-11
  type: socks5
  server: 184.178.172.11
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-12
  type: socks5
  server: 184.182.240.12
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-194
  type: socks5
  server: 184.181.217.194
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-13
  type: socks5
  server: 184.178.172.13
  port: 15311
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-201
  type: socks5
  server: 184.181.217.201
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-18
  type: socks5
  server: 184.178.172.18
  port: 15280
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-14
  type: socks5
  server: 184.178.172.14
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-197
  type: socks5
  server: 174.77.111.197
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-118
  type: socks5
  server: 68.71.242.118
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-33
  type: socks5
  server: 184.181.178.33
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ AT&T-210
  type: socks5
  server: 68.71.240.210
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-196
  type: socks5
  server: 174.77.111.196
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-12-2
  type: socks5
  server: 184.185.2.12
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-82
  type: socks5
  server: 174.64.199.82
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-55
  type: socks5
  server: 70.166.167.55
  port: 57745
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-23
  type: socks5
  server: 184.178.172.23
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-38
  type: socks5
  server: 70.166.167.38
  port: 57728
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-220
  type: socks5
  server: 184.181.217.220
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-26
  type: socks5
  server: 184.178.172.26
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-17
  type: socks5
  server: 184.178.172.17
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-211
  type: socks5
  server: 184.182.240.211
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-210
  type: socks5
  server: 184.181.217.210
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-28
  type: socks5
  server: 184.178.172.28
  port: 15294
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-198
  type: socks5
  server: 174.77.111.198
  port: 49547
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-3
  type: socks5
  server: 184.178.172.3
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-160
  type: socks5
  server: 70.166.65.160
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-79
  type: socks5
  server: 174.64.199.79
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-193
  type: socks5
  server: 174.75.211.193
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-222
  type: socks5
  server: 174.75.211.222
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-213
  type: socks5
  server: 184.181.217.213
  port: 4145
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-5
  type: socks5
  server: 184.178.172.5
  port: 15303
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-25
  type: socks5
  server: 184.178.172.25
  port: 15291
  udp: true
- name: ğŸ‡ºğŸ‡¸ Cox-206
  type: socks5
  server: 184.181.217.206
  port: 4145
  udp: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - DIRECT
  - ğŸ‡ºğŸ‡¸ AT&T-206
  - ğŸ‡ºğŸ‡¸ AT&T-14
  - ğŸ‡ºğŸ‡¸ AT&T-158
  - ğŸ‡ºğŸ‡¸ AT&T-134
  - ğŸ‡ºğŸ‡¸ AT&T-6
  - ğŸ‡ºğŸ‡¸ AT&T-38
  - ğŸ‡ºğŸ‡¸ AT&T-153
  - ğŸ‡ºğŸ‡¸ AT&T-130
  - ğŸ‡ºğŸ‡¸ AT&T-33
  - ğŸ‡ºğŸ‡¸ Cox-11
  - ğŸ‡ºğŸ‡¸ Cox-12
  - ğŸ‡ºğŸ‡¸ Cox-194
  - ğŸ‡ºğŸ‡¸ Cox-13
  - ğŸ‡ºğŸ‡¸ Cox-201
  - ğŸ‡ºğŸ‡¸ Cox-18
  - ğŸ‡ºğŸ‡¸ Cox-14
  - ğŸ‡ºğŸ‡¸ Cox-197
  - ğŸ‡ºğŸ‡¸ AT&T-118
  - ğŸ‡ºğŸ‡¸ Cox-33
  - ğŸ‡ºğŸ‡¸ AT&T-210
  - ğŸ‡ºğŸ‡¸ Cox-196
  - ğŸ‡ºğŸ‡¸ Cox-12-2
  - ğŸ‡ºğŸ‡¸ Cox-82
  - ğŸ‡ºğŸ‡¸ Cox-55
  - ğŸ‡ºğŸ‡¸ Cox-23
  - ğŸ‡ºğŸ‡¸ Cox-38
  - ğŸ‡ºğŸ‡¸ Cox-220
  - ğŸ‡ºğŸ‡¸ Cox-26
  - ğŸ‡ºğŸ‡¸ Cox-17
  - ğŸ‡ºğŸ‡¸ Cox-211
  - ğŸ‡ºğŸ‡¸ Cox-210
  - ğŸ‡ºğŸ‡¸ Cox-28
  - ğŸ‡ºğŸ‡¸ Cox-198
  - ğŸ‡ºğŸ‡¸ Cox-3
  - ğŸ‡ºğŸ‡¸ Cox-160
  - ğŸ‡ºğŸ‡¸ Cox-79
  - ğŸ‡ºğŸ‡¸ Cox-193
  - ğŸ‡ºğŸ‡¸ Cox-222
  - ğŸ‡ºğŸ‡¸ Cox-213
  - ğŸ‡ºğŸ‡¸ Cox-5
  - ğŸ‡ºğŸ‡¸ Cox-25
  - ğŸ‡ºğŸ‡¸ Cox-206
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡ºğŸ‡¸ AT&T-206
  - ğŸ‡ºğŸ‡¸ AT&T-14
  - ğŸ‡ºğŸ‡¸ AT&T-158
  - ğŸ‡ºğŸ‡¸ AT&T-134
  - ğŸ‡ºğŸ‡¸ AT&T-6
  - ğŸ‡ºğŸ‡¸ AT&T-38
  - ğŸ‡ºğŸ‡¸ AT&T-153
  - ğŸ‡ºğŸ‡¸ AT&T-130
  - ğŸ‡ºğŸ‡¸ AT&T-33
  - ğŸ‡ºğŸ‡¸ Cox-11
  - ğŸ‡ºğŸ‡¸ Cox-12
  - ğŸ‡ºğŸ‡¸ Cox-194
  - ğŸ‡ºğŸ‡¸ Cox-13
  - ğŸ‡ºğŸ‡¸ Cox-201
  - ğŸ‡ºğŸ‡¸ Cox-18
  - ğŸ‡ºğŸ‡¸ Cox-14
  - ğŸ‡ºğŸ‡¸ Cox-197
  - ğŸ‡ºğŸ‡¸ AT&T-118
  - ğŸ‡ºğŸ‡¸ Cox-33
  - ğŸ‡ºğŸ‡¸ AT&T-210
  - ğŸ‡ºğŸ‡¸ Cox-196
  - ğŸ‡ºğŸ‡¸ Cox-12-2
  - ğŸ‡ºğŸ‡¸ Cox-82
  - ğŸ‡ºğŸ‡¸ Cox-55
  - ğŸ‡ºğŸ‡¸ Cox-23
  - ğŸ‡ºğŸ‡¸ Cox-38
  - ğŸ‡ºğŸ‡¸ Cox-220
  - ğŸ‡ºğŸ‡¸ Cox-26
  - ğŸ‡ºğŸ‡¸ Cox-17
  - ğŸ‡ºğŸ‡¸ Cox-211
  - ğŸ‡ºğŸ‡¸ Cox-210
  - ğŸ‡ºğŸ‡¸ Cox-28
  - ğŸ‡ºğŸ‡¸ Cox-198
  - ğŸ‡ºğŸ‡¸ Cox-3
  - ğŸ‡ºğŸ‡¸ Cox-160
  - ğŸ‡ºğŸ‡¸ Cox-79
  - ğŸ‡ºğŸ‡¸ Cox-193
  - ğŸ‡ºğŸ‡¸ Cox-222
  - ğŸ‡ºğŸ‡¸ Cox-213
  - ğŸ‡ºğŸ‡¸ Cox-5
  - ğŸ‡ºğŸ‡¸ Cox-25
  - ğŸ‡ºğŸ‡¸ Cox-206
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
rules:
- GEOIP,LAN,DIRECT,no-resolve
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
